name: Deploy Preview (Dev)

on:
  push:
    branches: [gh-pages-dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:dev

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: oscto1/portfolio-dev
          publish_branch: gh-pages
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist